import { Product, Speciality, Brand, SiteSettings, HomepageContent } from '../types';

export const initialSiteSettings: SiteSettings = {
  businessName: 'New Pharma World',
  tagline: 'Your Trusted Pharmaceutical Partner',
  phone: '+91 98400 12345',
  phoneDisplay: '+91 98400 12345',
  whatsapp: '919840012345',
  whatsappDisplay: '+91 98400 12345',
  email: 'contact@newpharmaworld.com',
  addressLine1: 'No. 18, 1st Cross Street, Station View Road',
  addressLine2: 'Near Kodambakkam Railway Station',
  area: 'Kodambakkam',
  city: 'Chennai',
  state: 'Tamil Nadu',
  pincode: '600024',
  country: 'India',
  businessHours: 'Monday – Saturday: 9:00 AM – 8:30 PM | Sunday: Closed',
  googleMapsUrl: 'https://maps.google.com/?q=Kodambakkam,+Chennai+600024',
  googleMapsEmbed: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d15547.458239023403!2d80.2166!3d13.0524!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3a5266e74b7df7ab%3A0x6a19f4a0bfa1e6f!2sKodambakkam%2C%20Chennai%2C%20Tamil%20Nadu%20600024!5e0!3m2!1sen!2sin!4v1699999999999',
  facebookUrl: 'https://facebook.com',
  twitterUrl: 'https://twitter.com',
  linkedinUrl: 'https://linkedin.com',
  instagramUrl: 'https://instagram.com',
  disclaimer: 'Informational Notice: New Pharma World is an authorized pharmaceutical supplier. We provide genuine medicines to hospitals, clinics, licensed pharmacies, and authorized healthcare clients. The information presented on this website is for catalogue and enquiry purposes only and does not constitute medical advice, diagnosis, or prescription services.',
};

export const initialHomepageContent: HomepageContent = {
  hero: {
    badge: 'Authorized Pharmaceutical Supplier in Chennai',
    headline: 'Quality Medicines. Trusted Healthcare.',
    subtitle: 'Your Trusted Pharmaceutical Partner in Chennai',
    description: 'Genuine pharmaceutical products, trusted brands and reliable healthcare supply for hospitals, pharmacies, clinics and authorized customers.',
    heroImageUrl: 'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?q=80&w=1200&auto=format&fit=crop',
    primaryCtaText: 'Explore Products',
    primaryCtaLink: '/products',
    secondaryCtaText: 'Contact Us',
    secondaryCtaLink: '/contact',
  },
  trustIndicators: [
    {
      id: 'ti-1',
      title: 'Genuine Products',
      description: 'Authentic medicines sourced from trusted pharmaceutical manufacturers.',
      icon: 'ShieldCheck',
    },
    {
      id: 'ti-2',
      title: 'Trusted Brands',
      description: 'Quality products from established pharmaceutical companies.',
      icon: 'Award',
    },
    {
      id: 'ti-3',
      title: 'Competitive Pricing',
      description: 'Reliable pharmaceutical supply at competitive prices.',
      icon: 'Tag',
    },
    {
      id: 'ti-4',
      title: 'Reliable Service',
      description: 'Dependable order support and customer service.',
      icon: 'Truck',
    },
  ],
  aboutPreview: {
    badge: 'Who We Are',
    title: 'Dedicated Pharmaceutical Supply Partner',
    description: 'New Pharma World operates with a commitment to healthcare excellence, bridging the gap between world-class pharmaceutical manufacturers and healthcare providers across Tamil Nadu. Located in Kodambakkam, Chennai, we ensure authentic medicine availability and dependable supply chains.',
    highlight1: '100% Genuine & Batch-Tracked Products',
    highlight2: 'Specialized Handling for Temperature-Sensitive Formulations',
    highlight3: 'Dedicated Support for Hospitals, Clinics & Pharmacies',
    experienceYears: 'Trusted Healthcare Partner',
  },
  ctaBanner: {
    title: 'Looking for Specialized Pharmaceutical Supply?',
    description: 'Connect with our team for bulk enquiries, institutional supply, or specific medicine availability.',
    buttonText: 'Submit an Enquiry',
    buttonLink: '/enquiry',
  },
};

export const initialSpecialities: Speciality[] = [
  {
    id: 'transplant-medicine',
    name: 'Transplant Medicine',
    slug: 'transplant-medicine',
    description: 'Immunosuppressants and specialized post-transplant care medicines maintaining graft survival and patient health.',
    imageUrl: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?q=80&w=800&auto=format&fit=crop',
    iconName: 'Activity',
    displayOrder: 1,
    isActive: true,
  },
  {
    id: 'dialysis',
    name: 'Dialysis',
    slug: 'dialysis',
    description: 'Hemodialysis concentrates, peritoneal solutions, and renal care pharmaceuticals for clinical management.',
    imageUrl: 'https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?q=80&w=800&auto=format&fit=crop',
    iconName: 'HeartPulse',
    displayOrder: 2,
    isActive: true,
  },
  {
    id: 'vaccines',
    name: 'Vaccines',
    slug: 'vaccines',
    description: 'Cold-chain maintained pediatric and adult biological vaccines for comprehensive immunization programs.',
    imageUrl: 'https://images.unsplash.com/photo-1618961734760-466979ce35b0?q=80&w=800&auto=format&fit=crop',
    iconName: 'Syringe',
    displayOrder: 3,
    isActive: true,
  },
  {
    id: 'general-medicine',
    name: 'General Medicine',
    slug: 'general-medicine',
    description: 'Broad spectrum anti-infectives, analgesics, cardiovascular, and metabolic disorder formulations.',
    imageUrl: 'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?q=80&w=800&auto=format&fit=crop',
    iconName: 'Pill',
    displayOrder: 4,
    isActive: true,
  },
  {
    id: 'fertility',
    name: 'Fertility',
    slug: 'fertility',
    description: 'Reproductive endocrinology therapies, gonadotropins, and fertility support medications.',
    imageUrl: 'https://images.unsplash.com/photo-1583912267670-6575ad4736f8?q=80&w=800&auto=format&fit=crop',
    iconName: 'Sparkles',
    displayOrder: 5,
    isActive: true,
  },
  {
    id: 'cancer-care',
    name: 'Cancer Care',
    slug: 'cancer-care',
    description: 'Targeted oncologicals, chemotherapeutic agents, and supportive palliative care medicines.',
    imageUrl: 'https://images.unsplash.com/photo-1532938911079-1b06ac7ceec7?q=80&w=800&auto=format&fit=crop',
    iconName: 'ShieldAlert',
    displayOrder: 6,
    isActive: true,
  },
];

export const initialBrands: Brand[] = [
  {
    id: 'cipla',
    name: 'Cipla',
    logoUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?q=80&w=400&auto=format&fit=crop',
    description: 'Global pharmaceutical company focused on agile and affordable healthcare therapies.',
    websiteUrl: 'https://www.cipla.com',
    displayOrder: 1,
    isActive: true,
  },
  {
    id: 'sun-pharma',
    name: 'Sun Pharmaceutical',
    logoUrl: 'https://images.unsplash.com/photo-1563213126-a4273aed2016?q=80&w=400&auto=format&fit=crop',
    description: 'India’s largest specialty generic pharmaceutical company.',
    websiteUrl: 'https://www.sunpharma.com',
    displayOrder: 2,
    isActive: true,
  },
  {
    id: 'dr-reddys',
    name: "Dr. Reddy's",
    logoUrl: 'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?q=80&w=400&auto=format&fit=crop',
    description: 'Leading multinational pharmaceutical enterprise providing trusted medicines worldwide.',
    websiteUrl: 'https://www.drreddys.com',
    displayOrder: 3,
    isActive: true,
  },
  {
    id: 'lupin',
    name: 'Lupin',
    logoUrl: 'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?q=80&w=400&auto=format&fit=crop',
    description: 'Significant player in anti-tuberculosis, cardiovascular, and respiratory formulations.',
    websiteUrl: 'https://www.lupin.com',
    displayOrder: 4,
    isActive: true,
  },
  {
    id: 'zydus',
    name: 'Zydus',
    logoUrl: 'https://images.unsplash.com/photo-1584017911766-d451b3d0e843?q=80&w=400&auto=format&fit=crop',
    description: 'Innovative healthcare solutions and biosimilar manufacturer.',
    websiteUrl: 'https://www.zyduslife.com',
    displayOrder: 5,
    isActive: true,
  },
  {
    id: 'mankind',
    name: 'Mankind',
    logoUrl: 'https://images.unsplash.com/photo-1585435557343-3b092031a831?q=80&w=400&auto=format&fit=crop',
    description: 'Affordable and quality formulations across chronic and acute therapeutic segments.',
    websiteUrl: 'https://www.mankindpharma.com',
    displayOrder: 6,
    isActive: true,
  },
  {
    id: 'intas',
    name: 'Intas',
    logoUrl: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?q=80&w=400&auto=format&fit=crop',
    description: 'Global biosimilars and oncology formulations leader.',
    websiteUrl: 'https://www.intaspharma.com',
    displayOrder: 7,
    isActive: true,
  },
  {
    id: 'abbott',
    name: 'Abbott',
    logoUrl: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?q=80&w=400&auto=format&fit=crop',
    description: 'Global healthcare leader in diagnostics, medical devices, and established pharmaceuticals.',
    websiteUrl: 'https://www.abbott.com',
    displayOrder: 8,
    isActive: true,
  },
];

export const initialDemoProducts: Product[] = [
  {
    id: 'demo-tacrolimus-05',
    name: 'Tacrolimus Capsules 0.5mg (Demo Product)',
    genericName: 'Tacrolimus',
    brand: "Dr. Reddy's",
    category: 'Transplant Medicine',
    manufacturer: "Dr. Reddy's Laboratories Ltd.",
    description: 'Calcineurin inhibitor indicated for the prophylaxis of organ rejection in patients receiving allogeneic liver, kidney or heart transplants. Used in conjunction with other immunosuppressants.',
    dosageForm: 'Capsule',
    strength: '0.5 mg',
    packaging: 'Blister Pack of 10x10 Capsules',
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?q=80&w=600&auto=format&fit=crop',
    availability: 'In Stock',
    isFeatured: true,
    isActive: true,
    displayOrder: 1,
  },
  {
    id: 'demo-mycophenolate-500',
    name: 'Mycophenolate Mofetil 500mg Tablets (Demo Product)',
    genericName: 'Mycophenolate Mofetil',
    brand: 'Cipla',
    category: 'Transplant Medicine',
    manufacturer: 'Cipla Limited',
    description: 'Inosine monophosphate dehydrogenase (IMPDH) inhibitor used for the prophylaxis of renal, cardiac, or hepatic transplant rejection in conjunction with cyclosporine and corticosteroids.',
    dosageForm: 'Film-Coated Tablet',
    strength: '500 mg',
    packaging: '10 Strips of 10 Tablets',
    imageUrl: 'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?q=80&w=600&auto=format&fit=crop',
    availability: 'In Stock',
    isFeatured: true,
    isActive: true,
    displayOrder: 2,
  },
  {
    id: 'demo-erythropoietin-4000',
    name: 'Recombinant Erythropoietin 4000 IU (Demo Product)',
    genericName: 'Erythropoietin Alpha',
    brand: 'Intas',
    category: 'Dialysis',
    manufacturer: 'Intas Pharmaceuticals Ltd.',
    description: 'Biological formulation for the treatment of anemia associated with chronic renal failure in patients on hemodialysis or peritoneal dialysis.',
    dosageForm: 'Prefilled Syringe Injection',
    strength: '4000 IU / 0.4ml',
    packaging: 'Single Dose Prefilled Syringe',
    imageUrl: 'https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?q=80&w=600&auto=format&fit=crop',
    availability: 'In Stock',
    isFeatured: true,
    isActive: true,
    displayOrder: 3,
  },
  {
    id: 'demo-hemodialysis-fluid',
    name: 'Hemodialysis Concentrate Solution Part A & B (Demo Product)',
    genericName: 'Electrolyte Hemodialysis Solution',
    brand: 'Sun Pharmaceutical',
    category: 'Dialysis',
    manufacturer: 'Sun Pharmaceutical Industries Ltd.',
    description: 'Standard acid and bicarbonate dialysate concentrate formulations formulated for clinical artificial kidney hemodialysis procedures.',
    dosageForm: 'Liquid Concentrate',
    strength: 'Standard Clinical Ratio',
    packaging: '10 Litre / 20 Litre Canister',
    imageUrl: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?q=80&w=600&auto=format&fit=crop',
    availability: 'Available on Order',
    isFeatured: false,
    isActive: true,
    displayOrder: 4,
  },
  {
    id: 'demo-flu-vaccine',
    name: 'Quadrivalent Influenza Vaccine (Demo Product)',
    genericName: 'Inactivated Quadrivalent Influenza Vaccine',
    brand: 'Abbott',
    category: 'Vaccines',
    manufacturer: 'Abbott Healthcare',
    description: 'Cold-chain maintained seasonal influenza vaccination for active immunization against specific virus strains.',
    dosageForm: 'Prefilled Syringe (0.5ml)',
    strength: 'Seasonal WHO Strain',
    packaging: 'Single Dose Syringe with Needle',
    imageUrl: 'https://images.unsplash.com/photo-1618961734760-466979ce35b0?q=80&w=600&auto=format&fit=crop',
    availability: 'In Stock',
    isFeatured: true,
    isActive: true,
    displayOrder: 5,
  },
  {
    id: 'demo-paclitaxel-injection',
    name: 'Paclitaxel Injection 100mg/16.7ml (Demo Product)',
    genericName: 'Paclitaxel',
    brand: 'Cipla',
    category: 'Cancer Care',
    manufacturer: 'Cipla Ltd. (Oncology Division)',
    description: 'Microtubule inhibitor antineoplastic agent used in clinical oncology therapy regimens under specialist supervision.',
    dosageForm: 'Concentrate for Infusion',
    strength: '100 mg / 16.7 ml',
    packaging: 'Single Vial Box',
    imageUrl: 'https://images.unsplash.com/photo-1532938911079-1b06ac7ceec7?q=80&w=600&auto=format&fit=crop',
    availability: 'Available on Order',
    isFeatured: true,
    isActive: true,
    displayOrder: 6,
  },
  {
    id: 'demo-fsh-recombinant',
    name: 'Recombinant Human FSH 75 IU (Demo Product)',
    genericName: 'Follitropin Alpha',
    brand: 'Zydus',
    category: 'Fertility',
    manufacturer: 'Zydus Life Ltd.',
    description: 'Recombinant gonadotropin formulation prescribed in assisted reproduction technologies (ART) for controlled ovarian stimulation.',
    dosageForm: 'Subcutaneous Injection',
    strength: '75 IU',
    packaging: 'Vial with Solvent',
    imageUrl: 'https://images.unsplash.com/photo-1583912267670-6575ad4736f8?q=80&w=600&auto=format&fit=crop',
    availability: 'In Stock',
    isFeatured: false,
    isActive: true,
    displayOrder: 7,
  },
  {
    id: 'demo-amox-clav',
    name: 'Amoxicillin and Clavulanate Potassium 625mg (Demo Product)',
    genericName: 'Amoxicillin + Potassium Clavulanate',
    brand: 'Mankind',
    category: 'General Medicine',
    manufacturer: 'Mankind Pharma Ltd.',
    description: 'Broad-spectrum beta-lactam antibacterial combined with beta-lactamase inhibitor for respiratory, urinary, skin, and soft tissue infections.',
    dosageForm: 'Film-Coated Tablet',
    strength: '500mg Amox + 125mg Clav',
    packaging: 'Strip of 10 Tablets (Alu-Alu)',
    imageUrl: 'https://images.unsplash.com/photo-1584017911766-d451b3d0e843?q=80&w=600&auto=format&fit=crop',
    availability: 'In Stock',
    isFeatured: true,
    isActive: true,
    displayOrder: 8,
  },
];
